print("suraj111 -> ", "suraj111".isalnum())
print("suraj111 -> ", "suraj111".isalpha())
print("suraj111 ->", "suraj111".isdigit())
print("SURAJ INDAVE -> ", "SURAJ INDAVE".islower())
print("suraj indaved -> ", "suraj indaved".isupper())
print("Suraj Indave -> ", "Suraj Indave".istitle())
print("Suraj Indave -> ", "Suraj Indave".isspace())
print("indave suraj -> ", "indave suraj ".startswith("indve"))
print("indave suraj ", "indave suraj ".endswith("raj"))